

package vaccinatedreport1;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.*;

public class Booster_dose extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Booster_dose() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        conn = DbConnection.ConnecrDb();
        jTextVacName.setVisible(false);
    }
private void clearField()
{
    jTextPName.setText(null);
    jTextAge.setText(null);
    jTextMobNo.setText(null);
    jTextHosDes.setText(null);
    jTextPrice.setText(null);
    jTextAdhr.setText(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButtonSub = new javax.swing.JButton();
        jTextAdhr = new javax.swing.JTextField();
        jTextVacName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextMobNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextHosDes = new javax.swing.JTextField();
        jTextPName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxVacName = new javax.swing.JComboBox<>();
        jTextAge = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextGen = new javax.swing.JTextField();
        jTextDoseDt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSub.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonSub.setText("SUBMIT");
        jButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 119, 33));

        jTextAdhr.setEnabled(false);
        jTextAdhr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAdhrKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAdhrKeyTyped(evt);
            }
        });
        jPanel3.add(jTextAdhr, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 198, 26));

        jTextVacName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVacNameActionPerformed(evt);
            }
        });
        jPanel3.add(jTextVacName, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 510, 100, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("VACCINE NAME");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 222, 26));

        jTextMobNo.setEnabled(false);
        jTextMobNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextMobNoKeyTyped(evt);
            }
        });
        jPanel3.add(jTextMobNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 198, 30));

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setText(" BOOSTER DOSE FORM");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 356, 38));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("CONTACT NUMBER");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 222, 27));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("PATIENT NAME");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 222, -1));

        jTextHosDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextHosDesKeyTyped(evt);
            }
        });
        jPanel3.add(jTextHosDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 198, 30));

        jTextPName.setEnabled(false);
        jTextPName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPNameKeyTyped(evt);
            }
        });
        jPanel3.add(jTextPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 200, 26));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("HOSPITAL DESCRIPTION");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("AGE");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 222, 26));

        jComboBoxVacName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxVacName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COVAXIN", "COVISHEILD", "SPUTNIK", "PFTIZER", "OTHER" }));
        jComboBoxVacName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVacNameActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxVacName, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 148, 26));

        jTextAge.setEnabled(false);
        jTextAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAgeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAgeKeyTyped(evt);
            }
        });
        jPanel3.add(jTextAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 200, 26));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("PRICE");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 222, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("GENDER");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 222, 26));

        jTextPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPriceKeyTyped(evt);
            }
        });
        jPanel3.add(jTextPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, 198, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("AADHAR NUMBER");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 222, 26));

        jTextGen.setEnabled(false);
        jTextGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGenActionPerformed(evt);
            }
        });
        jPanel3.add(jTextGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 200, 30));
        jPanel3.add(jTextDoseDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 60, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinatedreport1/Does.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 1350, 690));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1510, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubActionPerformed
        // TODO add your handling code here:
        String sql="Insert into Tab_Booster values(?,?,?,?,?,?,?,?,?)";
        //for checking whether all the fields are filled or not
        if(jTextPName.getText().length()==0 ||jTextAdhr.getText().length()==0 || jTextAge.getText().length()==0|| jTextMobNo.getText().length()==0|| jTextHosDes.getText().length()==0 || jComboBoxVacName.getSelectedItem().toString().length()==0||jTextPrice.getText().length()==0)
            JOptionPane.showMessageDialog(null,"Please fill all the details");
        else
        {
            //for throwing all details into the database
            try
            {
                pst = conn.prepareStatement(sql);
                pst.setString(1,jTextPName.getText());
                pst.setString(2,jTextAge.getText());
                pst.setString(3,jTextGen.getText());
                pst.setString(4,jTextMobNo.getText());
                pst.setString(5,jTextHosDes.getText());
                if("OTHER".equals(jComboBoxVacName.getSelectedItem().toString()))
                {   pst.setString(6,jTextVacName.getText()); }
                else{
                pst.setString(6,jComboBoxVacName.getSelectedItem().toString());}
                pst.setString(7,jTextPrice.getText());
                LocalDate currentDate7 = LocalDate.now();
                LocalDate currentDatePlus7 = currentDate7.plusDays(28);
                System.out.println(currentDatePlus7);
                
                String cd7=currentDate7.format(DateTimeFormatter.ISO_DATE);
                jTextDoseDt.setText(cd7);
                pst.setString(8,jTextDoseDt.getText());
                pst.setString(9,jTextAdhr.getText());
                pst.execute();
                
                JOptionPane.showMessageDialog(null,"Inserted Successfully");
                clearField(); //for clearing all the fields after clicking submit button
                dispose();
                new BillB().setVisible(true);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_jButtonSubActionPerformed

    private void jTextPNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPNameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            jTextPName.setEditable(true);
        }
        else
        {
            jTextPName.setEditable(false);    
        }   
    }//GEN-LAST:event_jTextPNameKeyTyped

    private void jTextAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAgeKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        String age=jTextAge.getText();
        int len=age.length();
        if(Character.isDigit(c)&&(len<3))
        {
            jTextAge.setEditable(true);
        }
        else
        {
            jTextAge.setEditable(false);
        }
    }//GEN-LAST:event_jTextAgeKeyTyped

    private void jTextAdhrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAdhrKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        String adhr=jTextAdhr.getText();
        int len=adhr.length();
        if(Character.isDigit(c)&&(len<12))
        {
            jTextAdhr.setEditable(true);
        }
        else
        {
            jTextAdhr.setEditable(false);    
        }   
    }//GEN-LAST:event_jTextAdhrKeyTyped

    private void jTextMobNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMobNoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        String MobNo=jTextMobNo.getText();
        int len=MobNo.length();
        if((!(Character.isLetter(c)))&&(len<14))
        {
            jTextMobNo.setEditable(true);
        }
        else
        {
            jTextMobNo.setEditable(false);    
        }   
    }//GEN-LAST:event_jTextMobNoKeyTyped

    private void jTextHosDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextHosDesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHosDesKeyTyped

    private void jTextPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPriceKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        
        if(!(Character.isLetter(c)))
        {
            jTextPrice.setEditable(true);
        }
        else
        {
            jTextPrice.setEditable(false);    
        }  
    }//GEN-LAST:event_jTextPriceKeyTyped

    private void jTextAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAgeKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
        {
            jTextAge.setEditable(true);
        }
        else
        {
            jTextAge.setEditable(false);
        }
        
    }//GEN-LAST:event_jTextAgeKeyPressed

    private void jTextAdhrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAdhrKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
        {   jTextAdhr.setEditable(true);    }
        else
        {   jTextAdhr.setEditable(false);   }
    }//GEN-LAST:event_jTextAdhrKeyPressed

    private void jComboBoxVacNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVacNameActionPerformed
        // TODO add your handling code here:
        if(jComboBoxVacName.getSelectedItem().toString()=="OTHER")
        {   jTextVacName.setVisible(true);  }
        else
        {   jTextVacName.setVisible(false);   }
    }//GEN-LAST:event_jComboBoxVacNameActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jTextDoseDt.setVisible(false);
        jTextHosDes.requestFocus();
        String Adhar=UID_Form.jTextAdhr.getText();
        try{
            Connection d2_con = DriverManager.getConnection("jdbc:sqlite:C://sqlite//Vaccination_Report.db");
            
            Statement d2_stmt = d2_con.createStatement();
            
            String d2_SQL = "SELECT * FROM Tab_Dose2 WHERE Adhr = '" + Adhar + "'";
            ResultSet d2_rs = d2_stmt.executeQuery(d2_SQL);
            if(d2_rs.next())
            {
                //JOptionPane.showMessageDialog(null,"again, This UID is already Registered!");
                jTextPName.setText(d2_rs.getString("PName"));
                jTextAge.setText(d2_rs.getString("Age"));
                jTextMobNo.setText(d2_rs.getString("MobNo"));
                jTextGen.setText(d2_rs.getString("Gen"));
            }
            d2_rs.close();
        }
        catch (Exception e)
        {
            System.out.println("Error: " + e.getMessage());
        }
        jTextAdhr.setText(UID_Form.jTextAdhr.getText());
    }//GEN-LAST:event_formWindowActivated

    private void jTextGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGenActionPerformed

    private void jTextVacNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVacNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVacNameActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booster_dose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booster_dose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booster_dose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booster_dose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booster_dose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSub;
    private javax.swing.JComboBox<String> jComboBoxVacName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextAdhr;
    private javax.swing.JTextField jTextAge;
    private javax.swing.JTextField jTextDoseDt;
    private javax.swing.JTextField jTextGen;
    private javax.swing.JTextField jTextHosDes;
    private javax.swing.JTextField jTextMobNo;
    private javax.swing.JTextField jTextPName;
    private javax.swing.JTextField jTextPrice;
    private javax.swing.JTextField jTextVacName;
    // End of variables declaration//GEN-END:variables
}
