/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinatedreport1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author Anjali Baranwal
 */
public class Count extends javax.swing.JFrame {

    /**
     * Creates new form Count
     */
    public Count() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelB = new javax.swing.JLabel();
        jTextB = new javax.swing.JTextField();
        jText2 = new javax.swing.JTextField();
        jText1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextCVX = new javax.swing.JTextField();
        jTextCVS = new javax.swing.JTextField();
        jTextSPTNK = new javax.swing.JTextField();
        jTextOTHER = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jText3 = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("TOTAL NO. OF VACCINE USED");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, -1, 32));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DOSE I");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 68, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DOSE II");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, 34));

        jLabelB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelB.setText("BOOSTER DOSE");
        jPanel1.add(jLabelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, 34));

        jTextB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBActionPerformed(evt);
            }
        });
        jPanel1.add(jTextB, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 74, 34));

        jText2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText2ActionPerformed(evt);
            }
        });
        jPanel1.add(jText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 74, 34));

        jText1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText1ActionPerformed(evt);
            }
        });
        jPanel1.add(jText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 74, 34));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("RECORDS OF VACCINE USED: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, -1, 36));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("COVAXIN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 350, -1, 34));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("COVISHEILD");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, -1, 34));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("SPUTNIK");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 470, -1, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("OTHER");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 530, -1, 34));

        jTextCVX.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextCVX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCVXActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCVX, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 350, 74, 34));

        jTextCVS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextCVS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCVSActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCVS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 410, 74, 34));

        jTextSPTNK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextSPTNK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSPTNKActionPerformed(evt);
            }
        });
        jPanel1.add(jTextSPTNK, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 470, 74, 34));

        jTextOTHER.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextOTHER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextOTHERActionPerformed(evt);
            }
        });
        jPanel1.add(jTextOTHER, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 530, 74, 34));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText(" RECORDS OF DOSES ");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 274, 46));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("RECORDS OF DOSES GIVEN TO PATIENTS: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, 32));

        jText3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText3ActionPerformed(evt);
            }
        });
        jPanel1.add(jText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, 74, 34));

        jButtonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinatedreport1/spencer-davis-4oKXRdv9x7E-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 1310, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText1ActionPerformed

    private void jText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText2ActionPerformed

    private void jTextBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        try{
            Connection reg_con = DriverManager.getConnection("jdbc:sqlite:C://sqlite//Vaccination_Report.db");
            
            Statement stmt = reg_con.createStatement();
            ResultSet rs_1 = stmt.executeQuery("SELECT COUNT(*) AS rcount FROM Tab_Dose1");
            rs_1.next();
            int count= rs_1.getInt("rcount");
            rs_1.close();
            String s=Integer.toString(count);
            jText1.setText(s);
            
            ResultSet rs_2 = stmt.executeQuery("SELECT COUNT(*) AS rcount2 FROM Tab_Dose2");
            rs_2.next();
            int count2= rs_2.getInt("rcount2");
            rs_2.close();
            String s2=Integer.toString(count2);
            jText2.setText(s2);
            
            ResultSet rs_B = stmt.executeQuery("SELECT COUNT(*) AS rcountB FROM Tab_Booster");
            rs_B.next();
            int countB= rs_B.getInt("rcountB");
            rs_B.close();
            String sB=Integer.toString(countB);
            jTextB.setText(sB);
            
            ResultSet rs_cx1 = stmt.executeQuery("SELECT COUNT(*) AS rcountVCX FROM Tab_Dose1 where VacName='COVAXIN'");
            rs_cx1.next();
            int countVCX= rs_B.getInt("rcountVCX");
            rs_cx1.close();
            ResultSet rs_cx2 = stmt.executeQuery("SELECT COUNT(*) AS rcountVCX2 FROM Tab_Dose2 where VacName='COVAXIN'");
            rs_cx2.next();
            int countVCX2= rs_B.getInt("rcountVCX2");
            rs_cx2.close();
            ResultSet rs_cxB = stmt.executeQuery("SELECT COUNT(*) AS rcountVCXB FROM Tab_Booster where VacName='COVAXIN'");
            rs_cxB.next();
            int countVCXB= rs_B.getInt("rcountVCXB");
            rs_cxB.close();
            int cCX=countVCX+countVCX2+countVCXB;
            String sVCX=Integer.toString(cCX);
            jTextCVX.setText(sVCX);
            
            ResultSet rs_cs1 = stmt.executeQuery("SELECT COUNT(*) AS rcountVCS FROM Tab_Dose1 where VacName='COVIDSHEILD'");
            rs_cs1.next();
            int countVCS= rs_B.getInt("rcountVCS");
            rs_cs1.close();
            ResultSet rs_cs2 = stmt.executeQuery("SELECT COUNT(*) AS rcountVCS2 FROM Tab_Dose2 where VacName='COVIDSHEILD'");
            rs_cs2.next();
            int countVCS2= rs_B.getInt("rcountVCS2");
            rs_cs2.close();
            ResultSet rs_csB = stmt.executeQuery("SELECT COUNT(*) AS rcountVCSB FROM Tab_Booster where VacName='COVIDSHEILD'");
            rs_csB.next();
            int countVCSB= rs_B.getInt("rcountVCSB");
            rs_csB.close();
            int cCS=countVCS+countVCS2+countVCSB;
            String sVCS=Integer.toString(cCS);
            jTextCVS.setText(sVCS);
            
            ResultSet rs_sp1 = stmt.executeQuery("SELECT COUNT(*) AS rcountSPTNK FROM Tab_Dose1 where VacName='SPUTNIK'");
            rs_sp1.next();
            int countSPTNK= rs_B.getInt("rcountSPTNK");
            rs_sp1.close();
            ResultSet rs_sp2 = stmt.executeQuery("SELECT COUNT(*) AS rcountSPTNK2 FROM Tab_Dose2 where VacName='SPUTNIK'");
            rs_sp2.next();
            int countSPTNK2= rs_B.getInt("rcountSPTNK2");
            rs_sp2.close();
            ResultSet rs_spB = stmt.executeQuery("SELECT COUNT(*) AS rcountSPTNKB FROM Tab_Booster where VacName='SPUTNIK'");
            rs_spB.next();
            int countSPTNKB= rs_B.getInt("rcountSPTNKB");
            rs_spB.close();
            int cSP=countSPTNK+countSPTNK2+countSPTNKB;
            String sSPTNK=Integer.toString(cSP);
            jTextSPTNK.setText(sSPTNK);
            
            ResultSet rs_ot1 = stmt.executeQuery("SELECT COUNT(*) AS rcountOTHER FROM Tab_Dose1 where VacName='OTHER'");
            rs_ot1.next();
            int countOTHER= rs_B.getInt("rcountOTHER");
            rs_ot1.close();
            ResultSet rs_ot2 = stmt.executeQuery("SELECT COUNT(*) AS rcountOTHER2 FROM Tab_Dose2 where VacName='OTHER'");
            rs_ot2.next();
            int countOTHER2= rs_B.getInt("rcountOTHER2");
            rs_ot2.close();
            ResultSet rs_otB = stmt.executeQuery("SELECT COUNT(*) AS rcountOTHERB FROM Tab_Booster where VacName='OTHER'");
            rs_otB.next();
            int countOTHERB= rs_B.getInt("rcountOTHERB");
            rs_otB.close();
            int cOth=countOTHER+countOTHER2+countOTHERB;
            String sOTHER=Integer.toString(cOth);
            jTextOTHER.setText(sOTHER);
            
            int total=cCX+cCS+cSP+cOth;
            String sTOTAL=Integer.toString(total);
            jText3.setText(sTOTAL);
        }
        catch (Exception e)
        {
            System.out.println("Error: " + e.getMessage());
        }
        jText1.setEditable(false);
        jText2.setEditable(false);
        jTextB.setEditable(false);
    }//GEN-LAST:event_formWindowActivated

    private void jTextCVXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCVXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCVXActionPerformed

    private void jTextCVSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCVSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCVSActionPerformed

    private void jTextOTHERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextOTHERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextOTHERActionPerformed

    private void jTextSPTNKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSPTNKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSPTNKActionPerformed

    private void jText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText3ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        new UID_Form().setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Count.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Count.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Count.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Count.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Count().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jText1;
    private javax.swing.JTextField jText2;
    private javax.swing.JTextField jText3;
    private javax.swing.JTextField jTextB;
    private javax.swing.JTextField jTextCVS;
    private javax.swing.JTextField jTextCVX;
    private javax.swing.JTextField jTextOTHER;
    private javax.swing.JTextField jTextSPTNK;
    // End of variables declaration//GEN-END:variables
}
