
package vaccinatedreport1;
import java.awt.*;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.lang.*;
import javax.swing.*;
import java.sql.*;
import java.time.*;
//import java.awt.
import java.time.format.DateTimeFormatter;
public class Dose_2_Report extends javax.swing.JFrame {
    public Dose_2_Report() {
        initComponents();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrint = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelDoseDt = new javax.swing.JLabel();
        jLabelPName = new javax.swing.JLabel();
        jLabelHosDes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelVacName = new javax.swing.JLabel();
        jLabelMobNo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelGen = new javax.swing.JLabel();
        jLabelAdhar = new javax.swing.JLabel();
        jLabelAdhr = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelPrint.setBackground(new java.awt.Color(204, 255, 204));
        panelPrint.setPreferredSize(new java.awt.Dimension(634, 612));
        panelPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("DOSE TAKEN DATE");
        panelPrint.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 175, -1));

        jLabelDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDate.setText("DATE: ");
        panelPrint.add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 80, 20));

        jLabelDoseDt.setText(": ");
        panelPrint.add(jLabelDoseDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 250, -1));

        jLabelPName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPName.setText(": ");
        panelPrint.add(jLabelPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 250, 30));

        jLabelHosDes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHosDes.setText(": ");
        panelPrint.add(jLabelHosDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 250, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("VACCINE NAME");
        panelPrint.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 290, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("CONTACT NUMBER");
        panelPrint.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 250, -1));

        jLabelVacName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelVacName.setText(": ");
        panelPrint.add(jLabelVacName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 250, 20));

        jLabelMobNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMobNo.setText(": ");
        panelPrint.add(jLabelMobNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 250, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("PATIENT NAME");
        panelPrint.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 220, -1));

        jLabelAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAge.setText(": ");
        panelPrint.add(jLabelAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 250, -1));

        jLabelGen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelGen.setText(": ");
        panelPrint.add(jLabelGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 250, -1));

        jLabelAdhar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelAdhar.setText("AADHAR NUMBER");
        panelPrint.add(jLabelAdhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 250, -1));

        jLabelAdhr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAdhr.setText(": ");
        panelPrint.add(jLabelAdhr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 250, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("HOSPITAL DESCRIPTION");
        panelPrint.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel33.setText("AGE");
        panelPrint.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 175, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("GENDER");
        panelPrint.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 109, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText(" FINAL REPORT FOR COVID-19 VACCINATION ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPrint.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, 29));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Disclaimer : ");
        panelPrint.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 100, -1));

        jTextArea1.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText(" \n     1. Please keep this report card, which includes medical information about the vaccines you have received.\n     2. The certificate is computer generated and hence does not require any seal or signature in original.\n     3. The authenticity of this certificate can be verfied at same place where patient has taken vaccine dose.\n     4. Let the health care professional know if you have any medical conditions that could be considered \n         precautions, such as pregnancy or a compromised immune system.\n     5. The most important thing to do post-vaccination is to continue wearing masks, regularly washing, or\n         sanitizing your hands, maintaining physical distance,avoid crowded places and avoid touching surfaces.\n\n");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        panelPrint.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 590, 180));

        jButtonPrint.setText("PRINT");
        jButtonPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPrintMouseEntered(evt);
            }
        });
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        panelPrint.add(jButtonPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 73, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPrintMouseClicked
        // TODO add your handling code here:
        jButtonPrint.setVisible(false);
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                pf.setOrientation(PageFormat.LANDSCAPE);
                if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.95,1);

                panelPrint.print(g2);

                return Printable.PAGE_EXISTS;

            }
        });
        boolean ok = job.printDialog();
        if(ok){
            try{

                job.print();
                JOptionPane.showMessageDialog(null,"Printed Successfully");
                dispose();
            }
            catch (PrinterException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonPrintMouseClicked

    private void jButtonPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPrintMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrintMouseEntered

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
               String Adhar=UID_Form.jTextAdhr.getText();
try{
Connection d1_con = DriverManager.getConnection("jdbc:sqlite:C://sqlite//Vaccination_Report.db");

Statement d1_stmt = d1_con.createStatement();

String d1_SQL = "SELECT * FROM Tab_Dose2 WHERE Adhr = '" + Adhar + "'";
ResultSet d1_rs = d1_stmt.executeQuery(d1_SQL);
if(d1_rs.next())
{
//JOptionPane.showMessageDialog(null,"again, This UID is already Registered!");
jLabelPName.setText(d1_rs.getString("PName"));
jLabelAge.setText(d1_rs.getString("Age"));
jLabelMobNo.setText(d1_rs.getString("MobNo"));
jLabelGen.setText(d1_rs.getString("Gen"));
jLabelHosDes.setText(d1_rs.getString("HosDes"));
jLabelVacName.setText(d1_rs.getString("VacName"));
jLabelDoseDt.setText(d1_rs.getString("DoseDt"));
//jLabelNextDt.setText(d1_rs.getString("NextDt"));
LocalDate currentDate7 = LocalDate.now();
String cd7=currentDate7.format(DateTimeFormatter.ISO_DATE);
jLabelDate.setText(cd7);
}
d1_rs.close();
}
catch (Exception e)
{
System.out.println("Error: " + e.getMessage());
}

jLabelAdhr.setText(UID_Form.jTextAdhr.getText());
      

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dose_2_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dose_2_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dose_2_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dose_2_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dose_2_Report().setVisible(true);
            }
        });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdhar;
    private javax.swing.JLabel jLabelAdhr;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDoseDt;
    private javax.swing.JLabel jLabelGen;
    private javax.swing.JLabel jLabelHosDes;
    private javax.swing.JLabel jLabelMobNo;
    private javax.swing.JLabel jLabelPName;
    private javax.swing.JLabel jLabelVacName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelPrint;
    // End of variables declaration//GEN-END:variables
}
