/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinatedreport1;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import vaccinatedreport1.UID_Form.jButtonCount;

public class Log_In extends javax.swing.JFrame {

    /**
     * Creates new form Log_In
     */
    public Log_In() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonAdmin = new javax.swing.JRadioButton();
        jRadioButtonEmp = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextUName = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 574));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setText("VACCINATION REPORT ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        buttonGroup.add(jRadioButtonAdmin);
        jRadioButtonAdmin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButtonAdmin.setText("ADMIN");
        jRadioButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAdminActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        buttonGroup.add(jRadioButtonEmp);
        jRadioButtonEmp.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButtonEmp.setText("EMPLOYEE");
        jRadioButtonEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmpActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("USERNAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("PASSWORD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        jTextUName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextUName.setEnabled(false);
        jTextUName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 140, -1));

        jButtonLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonLogin.setText("LOG IN");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 150, 40));

        jPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPassword.setEnabled(false);
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 140, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinatedreport1/login sujeeeee.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 1330, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1516, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAdminActionPerformed
        // TODO add your handling code here:
        jTextUName.setEnabled(true);
        jPassword.setEnabled(true);
        jTextUName.requestFocus();
    }//GEN-LAST:event_jRadioButtonAdminActionPerformed

    private void jTextUNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUNameActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        if(!(jRadioButtonAdmin.isSelected())&&!(jRadioButtonEmp.isSelected()))
            JOptionPane.showMessageDialog(null, "Please select Admin / Employee!");
        else if(jTextUName.getText().length()==0||jPassword.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Please Enter Username & Password both!");
        }
        else
        {
        if(jRadioButtonAdmin.isSelected())
    {
        if(("Admin".equals(jTextUName.getText()))&&("123".equals(jPassword.getText())))
        {
            dispose();
            new UID_Form().setVisible(true);
//            new UID_Form().jButtonCount.setVisible(false);
//            new Progress_Bar().setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Wrong username/password, try again!");
    }//GEN-LAST:event_jButtonLoginActionPerformed
    if(jRadioButtonEmp.isSelected())
{
        if(("Emp".equals(jTextUName.getText()))&&("123".equals(jPassword.getText())))
        {
            dispose();
//            new Progress_Bar().setVisible(true);
            new UID_Form_1().setVisible(true);
            jButtonCount.setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(null, "Wrong username/password, try again!");
    }   
    }}
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void jRadioButtonEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmpActionPerformed
        // TODO add your handling code here:
        jTextUName.setEnabled(true);
        jPassword.setEnabled(true);
        jTextUName.requestFocus();
    }//GEN-LAST:event_jRadioButtonEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JRadioButton jRadioButtonAdmin;
    private javax.swing.JRadioButton jRadioButtonEmp;
    private javax.swing.JTextField jTextUName;
    // End of variables declaration//GEN-END:variables
}
