/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinatedreport1;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;


public class Registration_Form extends javax.swing.JFrame {

    /**
     * Creates new form Registration_Form
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Registration_Form() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        conn = DbConnection.ConnecrDb();
    }
private void clearField()
{
jTextPName.setText(null);
jTextMobNo.setText(null);
jTextAdhr.setText(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextPName = new javax.swing.JTextField();
        jTextAdhr = new javax.swing.JTextField();
        jTextMobNo = new javax.swing.JTextField();
        jButtonSub = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("MOBILE NO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, -1));

        jTextPName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextPName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPNameKeyTyped(evt);
            }
        });
        jPanel1.add(jTextPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 157, -1));

        jTextAdhr.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextAdhr.setEnabled(false);
        jTextAdhr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAdhrKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAdhrKeyTyped(evt);
            }
        });
        jPanel1.add(jTextAdhr, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 157, -1));

        jTextMobNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextMobNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMobNoActionPerformed(evt);
            }
        });
        jTextMobNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextMobNoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextMobNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 157, -1));

        jButtonSub.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonSub.setText("SUBMIT");
        jButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 119, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 78, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setText("REGISTRATION FORM ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("AADHAR NO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, 30));

        jLabel5.setBackground(new java.awt.Color(102, 0, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinatedreport1/Registation.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 1360, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextMobNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMobNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMobNoActionPerformed

    private void jButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubActionPerformed
        // TODO add your handling code here:
        String sql="Insert into Tab_Reg values(?,?,?)";
        if(jTextPName.getText().length()==0|| jTextAdhr.getText().length()==0||jTextMobNo.getText().length()==0)
        JOptionPane.showMessageDialog(null,"Please fill all the details");
        else
        {
            try
            {
                pst = conn.prepareStatement(sql);
                pst.setString(1,jTextPName.getText());
                pst.setString(2,jTextAdhr.getText());
                pst.setString(3,jTextMobNo.getText());
                pst.execute();
                clearField(); // for clering field method
                JOptionPane.showMessageDialog(null,"Inserted Successfully");
                dispose();
                new Dose_1().setVisible(true);
                
            }
            catch(HeadlessException | SQLException e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_jButtonSubActionPerformed

    private void jTextAdhrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAdhrKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        String adhr=jTextAdhr.getText();
        int len=adhr.length();
        if(Character.isDigit(c)&&(len<12))
        {
            jTextAdhr.setEditable(true);
        }
        else
        {
            jTextAdhr.setEditable(false);    
        }
    }//GEN-LAST:event_jTextAdhrKeyTyped

    private void jTextAdhrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAdhrKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
        {   jTextAdhr.setEditable(true);    }
        else
        {   jTextAdhr.setEditable(false);   }
    }//GEN-LAST:event_jTextAdhrKeyPressed

    private void jTextMobNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMobNoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        String MobNo=jTextMobNo.getText();
        int len=MobNo.length();
        if((!(Character.isLetter(c)))&&(len<14))
        {
            jTextMobNo.setEditable(true);
        }
        else
        {
            jTextMobNo.setEditable(false);    
        }   
    }//GEN-LAST:event_jTextMobNoKeyTyped

    private void jTextPNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPNameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            jTextPName.setEditable(true);
        }
        else
        {
            jTextPName.setEditable(false);
        }
    }//GEN-LAST:event_jTextPNameKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here
        if(UID_Form.jTextAdhr!=null)
        {
            jTextAdhr.setText(UID_Form.jTextAdhr.getText());
        }
        else
        {
            jTextAdhr.setText(UID_Form_1.jTextAdhr1.getText());
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextAdhr;
    public static javax.swing.JTextField jTextMobNo;
    public static javax.swing.JTextField jTextPName;
    // End of variables declaration//GEN-END:variables
}
